In [1]:
# Question1
from array import *
new_array=array('b',[1,2,3,4,5,6])
list=new_array.tolist()
print(list)

[1, 2, 3, 4, 5, 6]


In [3]:
# Question2
import numpy as np
p=np.arange(9).reshape(3,3)
print(p)
res=np.trace(p)
print(res)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [4]:
# Question3
import numpy as np
y = np.array([[4, 7, 9], [15, 8, 11]])
print("Number is bigger than 11", y[y>11])

Number is bigger than 11 [15]


In [8]:
# Question4
import numpy as np
x=np.array([(5,3),(2,4),(7,5)])
y=np.array([(4,5),(7,3),(8,6)])
z=np.array([x+y])
print(z)

[[[ 9  8]
  [ 9  7]
  [15 11]]]


In [9]:
# Question5
import numpy as np
a= np.random.randint(2, 10, size=(2,5))
print(a)
b = a- a.mean(axis=1, keepdims=True)
print(b)

[[4 4 2 5 2]
 [5 5 2 7 2]]
[[ 0.6  0.6 -1.4  1.6 -1.4]
 [ 0.8  0.8 -2.2  2.8 -2.2]]
